# Generated by Django 3.2.5 on 2021-07-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_from', models.CharField(max_length=24)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, 
                                           primary_key=True, 
                                           serialize=False, 
                                           verbose_name='ID')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('buy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
    ]
