# Generated by Django 3.2.5 on 2021-09-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0002_auto_20210903_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={},
        ),
    ]
