# Generated by Django 3.2.5 on 2021-09-15 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0003_auto_20210915_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.CASCADE, # noqa
                                    to='currency_app.source',
                                    to_field='name'),
        ),
    ]
