# Generated by Django 3.2.5 on 2021-09-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0004_auto_20210915_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  # noqa
                                    to='currency_app.source',
                                    to_field='name'),
        ),
    ]
