# Generated by Django 3.2.5 on 2021-09-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0005_alter_rate_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.PositiveIntegerField()),
                ('path', models.CharField(max_length=255)),
                ('response_time', models.PositiveIntegerField()),
            ],
        ),
    ]
