# Generated by Django 3.2.5 on 2021-09-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0006_responselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar'),
                                            ('EUR', 'Euro'),
                                            ('UAH', 'Hryvna'),
                                            ('RUB', 'Ruble'),
                                            ('GBP', 'Pound'),
                                            ('CHF', 'Franc')],
                                   max_length=3),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='response_time',
            field=models.PositiveIntegerField(help_text='In milliseconds'),
        ),
    ]
