# Generated by Django 3.2.5 on 2021-09-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0007_auto_20210921_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='responselog',
            name='request_methods',
            field=models.CharField(choices=[('POST', 'POST'),
                                            ('GET', 'GET')],
                                   default='GET', max_length=10),
        ),
    ]
